const images = {
  mockProfilePic1: require("./mocks/fake-profile1.jpeg"),
  mockProfilePic2: require("./mocks/fake-profile2.jpeg"),
  mockProfilePic3: require("./mocks/fake-profile3.jpg"),
  mockProfilePic4: require("./mocks/fake-profile4.jpg"),
  mockProfilePic5: require("./mocks/fake-profile5.jpg"),
  mockProfilePic6: require("./mocks/fake-profile6.jpeg"),
  mockProfilePic7: require("./mocks/fake-profile7.jpeg"),
  mockProfilePic8: require("./mocks/fake-profile8.jpeg"),
  mockProfilePic9: require("./mocks/fake-profile9.jpeg"),
  x1Combo: require("./icons/x1-combo.png"),
  x2Combo: require("./icons/x2-combo.png"),
  x3Combo: require("./icons/x3-combo.png"),
  x4Combo: require("./icons/x4-combo.png"),
  x5Combo: require("./icons/x5-combo.png"),
  kapaiiLogo: require("./logo/kapaii-horizontal-logo.png"),
  kapaiiSquareLogo: require("./logo/kapaii-square-logo.jpeg"),
  kapaiiSquareLogoLight: require("./logo/kapaii-square-logo-light.png"),
  cashReward: require("./cash-reward-placeholder.jpg"),
  fbIcon: require("./icons/fb-icon.png"),
  googleIcon: require("./icons/google-icon.png"),
  defaultUser: require("./icons/default-user.png"),
  add: require("./icons/add.png"),
  trophy: require("./icons/trophy.png"),
  confettiAnimation: require("./animations/confetti-animation.json"),
  confettiAnimation2: require("./animations/confetti-animation2.json"),
  celebrationAnimation: require("./animations/celebration.json"),
  redeemAnimation: require("./animations/redeem-animation.json"),
  team: require("./illustrations/team.png"),
  clientTutorial1: require("./tutorials/client-tutorial-1.gif"),
  clientTutorial2: require("./tutorials/client-tutorial-2.gif"),
  clientTutorial3: require("./tutorials/client-tutorial-3.gif"),
  trainerTutorial2: require("./tutorials/trainer-tutorial-2.gif"),
  trainerTutorial3: require("./tutorials/trainer-tutorial-3.gif"),
  placeholderVideo: require("./placeholder-video.png"),
};

export default images;
